---
# Concourse task
platform: linux

image_resource:
  type: docker-image
  source:
    repository: mkenney/npm
    tag: 'node-6.9-alpine'

inputs:
- name: resource-web-cra

run:
  path: npm
  args: ["build"]